config/routes.rb
Medrx::Application.routes.draw do

  resources :doctors

  resources :patients do
    member do
      get "medications"
      post "new_medication"
      get "delete_medication"
    end
  end

  resources :doctors do
    collection do
      get 'dashboard'
    end
  end

  resources :profiles

  devise_for :users

  match '/home' => "home#dashboard", as: 'home_dashboard', via: :all
  root :to => "home#index"

  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
  belongs_to :doctor

  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_one :profile, :through => :user

  #validates :first_name, presence: true
  validates :device_no, presence: true, uniqueness: true

  accepts_nested_attributes_for :user

  #before_validation :password_generation
  #def password_generation
  #  password_confirmation = password = Devise.friendly_token.first(7) if password.nil? || password.blank?
  #end

  def age
    return nil if self.profile and self.profile.date_of_birth.nil?
    dob = self.profile.date_of_birth
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy, :medications, :new_medication, :delete_medication]

  # GET /patients
  # GET /patients.json
  def index
    if current_user and current_user.doctor
      @patients = current_user.doctor.patients
    else
      redirect_to doctors_path, notice: 'Update profile Role.'
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
    @patient.build_user
    @patient.build_user.build_profile
  end

  # GET /patients/1/edit
  def edit
  end


  # POST /patients
  # POST /patients.json
  def create
    #@patient = Patient.new(patient_params)
    #raise patient_params.to_yaml

    patient_parameters = patient_params
    patient_parameters[:user_attributes][:password] = patient_parameters[:user_attributes][:password_confirmation] = Devise.friendly_token.first(7)
    @patient = current_user.doctor.patients.new(patient_parameters)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  def medications
    @patient_medications = @patient.patient_medications
  end

  def new_medication
    @patient.patient_medications.create(:medication_id => params[:patient_medication][:medication_id])
    redirect_to medications_patient_path(@patient)
  end

  def delete_medication
    patient_medication = @patient.patient_medications.find(params[:patient_medication_id])
    patient_medication.destroy unless patient_medication.nil?
    redirect_to medications_patient_path(@patient)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      #params[:patient].permit(:diagnosis, :device_no)
      params.require(:patient).permit(:device_no, user_attributes: [:id, :email, :username, :password, :password_confirmation, profile_attributes:[:first_name,:last_name,:date_of_birth, :gender]])
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for @patient, html: {class: 'form-horizontal'} do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
      <%= f.label 'Device no.', class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= f.text_field :device_no, class: 'form-control' %>
      </div>
    </div>

    <%= f.fields_for :user do |user_form| %>

        <div class="form-group">
          <%= user_form.label :email, class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= user_form.text_field :email, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= user_form.label :username, class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= user_form.text_field :username, class: 'form-control' %>
          </div>
        </div>

        <%= user_form.fields_for :profile do |profile_form| %>
            <div class="form-group">
              <%= profile_form.label :first_name, class: 'col-sm-2 control-label' %>
              <div class="col-sm-4">
                <%= profile_form.text_field :first_name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= profile_form.label :last_name, class: 'col-sm-2 control-label' %>
              <div class="col-sm-4">
                <%= profile_form.text_field :last_name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= profile_form.label :gender, class: 'col-sm-2 control-label' %>
              <div class="col-sm-4">
                <label class="radio-inline">
                  <%= profile_form.radio_button :gender, 'male' %>Male
                </label>

                <label class="radio-inline">
                  <%= profile_form.radio_button :gender, 'female' %>Female
                </label>
              </div>
            </div>

            <div class="form-group">
              <%= profile_form.label :date_of_birth, class: 'col-sm-2 control-label' %>
              <div class="col-sm-4">
                <%= profile_form.date_select :date_of_birth, class: 'form-control' %>
              </div>
            </div>
        <% end %>
    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/patients/_new_medication.html.erb
<%= form_for new_patient_medication, url: new_medication_patient_path , html: {class: 'form-inline'} do |f| %>

    <%= hidden_field_tag(:patient_id, patient.id)%>
    <div class="form-group">
      <%= f.label 'capsule_name.', class: 'sr-only' %>
      <% medications_array = Medication.all.map { |medication| [medication.name, medication.id] } %>
      <%= f.select :medication_id, options_for_select(medications_array),{}, {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <label class="sr-only" for="exampleInputPassword2">Dosage</label>
      <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Dosage">
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table class="table">
  <thead>
    <tr>
      <th>Device no</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Created At</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.device_no, edit_patient_path(patient)  %></td>
        <td><%= patient.profile.first_name %></td>
        <td><%= patient.profile.last_name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.profile.gender %></td>
        <td><%= patient.created_at.localtime %></td>
        <td><%= link_to 'Medication', medications_patient_path(patient) %></td>
        <td><%#= link_to 'Destroy', delete_medication_patient(patient), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/medications.html.erb
<h1>Patient Medication</h1>
<% patient = @patient %>

 <div class="row">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Device no</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Created At</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= link_to patient.device_no, edit_patient_path(patient)  %></td>
        <td><%= patient.profile.first_name %></td>
        <td><%= patient.profile.last_name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.profile.gender %></td>
        <td><%= patient.created_at.localtime %></td>
      </tr>
      </tbody>
    </table>
 </div>
<hr>

 <div class="row">
    <% new_patient_medication = PatientMedication.new %>
    <%= render 'new_medication', :new_patient_medication => new_patient_medication, :patient => patient %>
 </div>

<hr>

 <div class="row">
    <table class="table">
      <tr>
        <th>Capsule</th>
        <th>Dosage</th>
        <th></th>
        <th></th>
      </tr>
      <% @patient_medications.each do |patient_medication| %>
          <tr>
            <td><%= patient_medication.medication.name %></td>
            <td><%#= patient_medication.dosage %>Daily 2 times</td>
            <td><%= link_to 'Edit', '#' %></td>
            <td><%= link_to 'Destroy', delete_medication_patient_path(:patient_medication_id => patient_medication.id), data: {confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </table>
 </div>
<br>
<hr>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>Device No. : <%= @patient.device_no %></p>
<p>Username. : <%= @patient.user.username %></p>
<p>Email. : <%= @patient.user.email %></p>
<p>Device No. : <%= @patient.device_no %></p>
<p>First name : <%= @patient.profile.first_name %></p>
<p>Last name : <%= @patient.profile.last_name %></p>
<p>Gender : <%= @patient.profile.gender %></p>
<p>Date of Birth : <%= @patient.profile.date_of_birth %></p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>