config/routes.rb
Medrx::Application.routes.draw do

  resources :doctors

  resources :patients do
    member do
      get "medications"
      post "new_medication"
      get "delete_medication"
    end
  end

  resources :doctors do
    collection do
      get 'dashboard'
    end
  end

  resources :profiles

  devise_for :users

  match '/home' => "home#dashboard", as: 'home_dashboard', via: :all
  root :to => "home#index"

  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :user
  has_many :patients, dependent: :destroy
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctor = current_user.doctor
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor }
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params[:doctor]
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<div class="row">
  <div class="page-header">
    <h1>Dashboard</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-info">
      <div class="panel-heading">Patients</div>
      <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
          <li class="active">
            <%= link_to patients_path do %>
              <i class="glyphicon glyphicon-user"></i> Patients
            <% end %>
          </li>
          <li>
            <%= link_to '' do %>
                <i class="glyphicon glyphicon-user"></i> Alert Log
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>