config/routes.rb
Medrx::Application.routes.draw do

  resources :doctors

  resources :patients do
    member do
      get "medications"
      post "new_medication"
      get "delete_medication"
    end
  end

  resources :doctors do
    collection do
      get 'dashboard'
    end
  end

  resources :profiles

  devise_for :users

  match '/home' => "home#dashboard", as: 'home_dashboard', via: :all
  root :to => "home#index"

  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">MedRx</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="header-navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li>
          <%= link_to home_dashboard_path do%>
            <i class="glyphicon glyphicon-home"></i> Dashboard
          <% end %>
        </li>
        <li>
          <p class="navbar-text navbar-right">
            Signed in as <%= link_to current_user.username, profile_path(current_user.profile.id) %>
          </p>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-off"></span> Sign out
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-user"></span> Signin
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-registration-mark"></span> Signup
          <% end %>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedRx</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <%= render :partial => 'layouts/header' %>
</div>
<div class="container">
  <%= content_tag :div, :id => "flash-message" do %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do %>
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      <% end %>
    <% end %>
  <% end %>
  <%= yield %>
</div>
<div class="footer"></div>

</body>
</html>